Feat/generation functions
kubeshop/tracetest pull request #1015
Opened 2022-07-28 21:15 UTC by mathnogueira

This PR...

## Changes

-

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-07-29 01:16 UTC, mathnogueira commented
This implements the feature request described in #948

2022-07-29 12:45 UTC, schoren requested changes

2022-07-29 12:45 UTC, schoren commented on server/executor/functions/function_registry.go
> +type FunctionRegistry interface {
You don't need to repeat the word `Function`, it's already in the package: https://michaelwhatcott.com/go-code-that-stutters/

2022-07-29 12:45 UTC, schoren commented on server/executor/functions/functions.go
> +type FunctionInvoker func(args ...FunctionArg) string
Same for everything. It's a lot easier to read and write `functions.Arg` than `functions.FunctionArg`

2022-07-29 12:45 UTC, schoren commented on server/executor/functions/functions.go
> +type FunctionArgConfig struct {
This could be written as:
````
type ArgConfig struct {
	Count int
  Types   []string
}
```

2022-07-29 12:45 UTC, schoren commented on server/executor/functions/parser.go
> +func ParseFunction(input string) (Function, []FunctionArg, error) {
```suggestion
func Parse(input string) (Function, []Arg, error) {
```

2022-07-29 12:45 UTC, schoren commented on server/executor/replacer/replacer.go
> +	if defaultInjector == nil {
I'd move this to an `init` func, or directly to the var init, like:
```
var defaultInjector = NewInjector()
```

2022-08-12 15:02 UTC, schoren requested changes
Looking great! there are a few details that needs attention, but the implementation is awesome

2022-08-12 15:02 UTC, schoren commented on server/executor/replacer/replacer.go
> +var defaultInjector *Injector = nil
Do we really need this to be a reference? It can be made a direct instance:

```suggestion
var defaultInjector Injector = NewInjector()
```

2022-08-12 15:24 UTC, mathnogueira commented on server/executor/functions/functions.go
> +	Count int
Yes it can :facepalm:

2022-08-12 16:18 UTC, schoren approved these changes
Left a suggestion based on personal preference, so feel free to ignore it. otherwise LGTM!

2022-08-12 16:18 UTC, schoren commented on server/executor/functions/functions.go
> +type ArgConfig struct {
Suggestion: since this is now a single field type, can it be converted to an alias?

```suggestion
type ArgTypes []string
```

2022-08-12 17:27 UTC, merged