remove loading
kubeshop/tracetest pull request #1221
Opened 2022-09-14 20:49 UTC by cescoferraro

This PR make the body fields of the create test form be a JSON editor with proper form validation

## Changes

- the body field 

## Fixes

- #1206 

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-09-15 18:30 UTC, xoscar requested changes
Hey @cescoferraro I left some questions and concerns. Let me know what you think

2022-09-15 23:18 UTC, cescoferraro commented on web/.npmrc
> +legacy-peer-deps=true
yes

2022-09-15 23:30 UTC, cescoferraro commented on web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/RequestDetailsForm.tsx
> -import {Form, Input} from 'antd';
i think the metadata field is an object. this object deals with a string
I think it can be done, but maybe in a separate ticket

2022-09-16 16:43 UTC, cescoferraro commented
https://www.loom.com/share/8d08d1b1fb7644ca8a5075721d64d42e

2022-09-17 12:14 UTC, xoscar commented on web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/useBodyMode.tsx
> +    if (!initialized) {
nested ifs can be usually simplified by having an `and` operation with a single if like:

`if(!initialized && isEditing && body)`

Then maybe we can have the rest of the validation logic at the Validator utility level and we can call it like `getBodyType(body)`

2022-09-17 12:16 UTC, xoscar commented on web/src/components/CreateTestPlugins/Rest/steps/RequestDetails/BodyField/BodyFieldContainer.tsx
> +export const BodyFieldContainer = styled.div<{bodyMode: BodyMode}>`
Can we just pass a boolean to this component? so we can do, $isDisplaying, and the logic to match the body type can be done at the parent level

2022-09-17 12:17 UTC, xoscar commented on web/src/services/Triggers/Postman.service.tsx
> +import {Collection, Item, ItemGroup, Request, RequestAuthDefinition, VariableDefinition} from 'postman-collection';
Is this change required?

2022-09-19 16:10 UTC, xoscar commented on web/src/components/Header/HeaderMenu.tsx
> +  const {isTriggerVisible, onCloseTrigger, setIsTriggerVisible} = useGuidedTour();
hey I think this pr is leaking some of the onboarding changes

2022-09-19 18:03 UTC, xoscar approved these changes

2022-09-20 03:35 UTC, merged