Create new onboarding expirience
kubeshop/tracetest pull request #1250
Opened 2022-09-20 04:52 UTC by cescoferraro

This PR creates the new onboarding expirience by this design https://www.figma.com/file/TMShLwGmcTwX7uRodvyRoE/Onboarding

## Changes

- Add New design

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-09-20 14:49 UTC, xoscar requested changes
Hey @cescoferraro I found a weird visual bug

![2022-09-20 16 48 05](https://user-images.githubusercontent.com/11051031/191290186-233a04cf-65ad-4294-8767-a0633d89eb86.gif)

Also, when clicking outside the onboarding popup it closes and ends the onboarding process.
And when you click prev the positions are wrong.

2022-09-21 21:31 UTC, cescoferraro commented
@jorgeepc @xoscar the issue reported by oscar in the last comment is because our different modes (Trigger/Trace/Test) are placed on different URLs. 
So when the onboarding goes from one URL to another, the next step component is not rendered. So the tour does not know where to place the dialog.
To solve the issue I have added 2 other steps, so we can showcase the Tabs Header while we navigate to the Test Mode so the glitch does not work on the proposed onboarding.

2022-09-28 08:50 UTC, xoscar commented
@cescoferraro I'm still seeing the weird behavior on some of the steps where it starts to shake. It also still has the issue that clicking elsewhere on the screen would close the onboarding.

2022-09-28 13:03 UTC, cescoferraro commented
@xoscar but closing when clicking elsewhere on the screen is the default behavior.
The shaking thing is hard to prevent when switching URLs. I think I need to give it a try with another library.
There is no way of making react-tour delay the navigating before presenting the new step.

2022-10-04 19:48 UTC, xoscar commented on web/package.json
> +    "react-use": "17.4.0",
Should we remove the react tour dependency if we are not using it anymore?

2022-10-04 22:15 UTC, xoscar approved these changes
Pre approving, GJ @cescoferraro

2022-10-05 18:08 UTC, merged