feat: config deprecation
kubeshop/tracetest pull request #2015
Opened 2023-02-17 20:02 UTC by mathnogueira

This PR allows us to deprecate configuration fields and notify the user about them.

![Screenshot from 2023-02-17 17-02-29](https://user-images.githubusercontent.com/2704737/219781286-23032f79-e0e9-4b6e-bca6-be6b267be612.png)

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-02-17 20:05 UTC, mathnogueira commented on server/config/server.go
> +	},
Added this so we have a warning about this setting.

2023-02-17 20:10 UTC, danielbdias approved these changes

2023-02-22 21:16 UTC, schoren requested changes
Great work! I think the test relying on writing files to disk needs to be improved, but I like the new apprach!

2023-02-23 18:37 UTC, schoren approved these changes
LGTM! Thanks for dealing with my annoying request!

2023-02-23 19:25 UTC, danielbdias approved these changes

2023-02-23 19:29 UTC, merged