docs: add analyzer plugins and rules documentation
kubeshop/tracetest pull request #2890
Opened 2023-07-07 22:41 UTC by jorgeepc

This PR...

## Changes

-

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2023-07-10 11:37 UTC, adnanrahic requested changes
Added a few suggestions.

Also, I see some files are using snake case.
Can you change to use `-` instead? This would keep it uniform to all files in the docs.
Also, some files do not have H1 titles, and are just using the filename in snake case. Could you add H1 titles with words? Eg. Instead of `ensures_no_api_key_leak` it would be `Ensures No API Keys Leak`, etc.

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/plugin-otel.md
> +The `Open Telemetry Semantic Conventions` plugin is responsible of analyzing the spans that are part of a trace in order to identify problematic patterns. The set of rules follows the OpenTelemetry c
```suggestion
The `OpenTelemetry Semantic Conventions` plugin analyzes the spans that are part of a trace to identify problematic patterns. The set of rules follows the OpenTelemetry conventions to ensure the quality of the telemetry data.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/plugin-security.md
> +The `Security` plugin is responsible of analyzing the spans that are part of a trace in order to identify security problems in the distributed system.
```suggestion
The `Security` plugin is responsible for analyzing the spans that are part of a trace in order to identify security problems in the distributed system.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/attribute_naming.md
> +Enforce attribute keys to follow common specifications
```suggestion
Enforce attribute keys to follow common specifications.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/attribute_naming.md
> +An Attribute is a key-value pair, which is encapsulated as part of a span. The attribute key should follow a set of common specifications to be considered valid.
```suggestion
An `Attribute` is a key-value pair, which is encapsulated as part of a span. The attribute key should follow a set of common specifications to be considered valid.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/attribute_naming.md
> +The following OTel semantic conventions for attribute keys are defined:
```suggestion
The following OpenTelemetry Semantic Conventions for attribute keys are defined:
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/enforce_dns.md
> +Enforce usage of DNS instead of IP addresses
```suggestion
Enforce usage of DNS instead of IP addresses.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/enforce_dns.md
> +- `"error"` requires dns over IP addresses
```suggestion
- `"error"` requires DNS over IP addresses
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/enforce_dns.md
> +- `"disabled"` disables the dns over IP addresses verification
```suggestion
- `"disabled"` disables the DNS over IP addresses verification
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/enforce_dns.md
> +- `"warning"` verifies dns over IP addresses but does not impact the analyzer score
```suggestion
- `"warning"` verifies DNS over IP addresses but does not impact the analyzer score
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/enforce_https_protocol.md
> +Enforce usage of secure protocol for HTTP server spans
```suggestion
Enforce usage of secure protocol for HTTP server spans.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/ensures_no_api_key_leak.md
> +Disallow leaked api keys for HTTP spans
```suggestion
Disallow leaked API keys for HTTP spans.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/ensures_no_api_key_leak.md
> +This rule disallows the record of api keys in HTTP spans.
```suggestion
This rule disallows the recording of API keys in HTTP spans.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/ensures_no_api_key_leak.md
> +- `"error"` requires not leaked api keys for HTTP spans
```suggestion
- `"error"` requires no leaked API keys for HTTP spans
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/ensures_no_api_key_leak.md
> +- `"disabled"` disables the no leaked api keys verification for HTTP spans
```suggestion
- `"disabled"` disables the no leaked API keys verification for HTTP spans
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/ensures_no_api_key_leak.md
> +- `"warning"` verifies not leaked api keys for HTTPS spans but does not impact the analyzer score
```suggestion
- `"warning"` verifies no leaked API keys for HTTPS spans but does not impact the analyzer score
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/ensures_no_api_key_leak.md
> +If you intentionally record api keys for HTTP spans then you can disable this rule.
```suggestion
If you intentionally record API keys for HTTP spans then you can disable this rule.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/not_empty_attributes.md
> +An Attribute is a key-value pair, which is encapsulated as part of a span. The attribute value should should not be empty to be considered valid.
```suggestion
An `Attribute` is a key-value pair, which is encapsulated as part of a span. The attribute value should not be empty to be considered valid.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/required_attributes.md
> +Enforce required attributes by span type
```suggestion
Enforce required attributes by span type.
```

2023-07-10 11:37 UTC, adnanrahic commented on docs/docs/analyzer/rules/span_naming.md
> +Enforce span names that identify a class of Spans, rather than individual Span instances
```suggestion
Enforce span names that identify a class of Spans, rather than individual Span instances.
```

2023-07-10 15:48 UTC, jorgeepc commented
> Added a few suggestions.
> 
> Also, I see some files are using snake case. Can you change to use `-` instead? This would keep it uniform to all files in the docs. Also, some files do not have H1 titles, and are just using the filename in snake case. Could you add H1 titles with words? Eg. Instead of `ensures_no_api_key_leak` it would be `Ensures No API Keys Leak`, etc.

Hey @adnanrahic thanks for the view. I updated the files based on your comments.

About `some files do not have H1 titles, and are just using the filename in snake case...`, the idea is to create a unique `ID` for each rule. This ID is going to be used in the backend and also we wanted to display it in the web app. So, we want to have something similar to the eslint [docs](https://eslint.org/docs/latest/rules/no-throw-literal). Please let me know your opinion.

![Screenshot 2023-07-10 at 10 47 17](https://github.com/kubeshop/tracetest/assets/3879892/1b72f243-8459-42b2-86ad-f8fa83b6635a)

2023-07-11 10:01 UTC, adnanrahic commented
Thanks for the explanation @jorgeepc ! 🙌 

That's actually pretty cool. Yeah, let's do it like you guys envisioned.

One small note I just noticed. Can you add a redirect in the `docusaurus.config.js` making sure the old concepts page for the analyzer redirects to the new concepts page?

2023-07-11 16:45 UTC, merged