Cypress Docs
kubeshop/tracetest pull request #3487
Opened 2024-01-02 20:17 UTC by xoscar

This PR adds the initial Cypress documentation

## Changes

- Adds Cypress docs

## Checklist

- [x] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2024-01-02 20:31 UTC, kdhamric commented on docs/docs/tools-and-integrations/cypress.mdx
> +Cypress is currently one of the top e2e testing frameworks, it is a great tool in its own right that allows you to replicate most of the production challenges you might encounter by allowinig develop
allowinig should be allowing

2024-01-02 20:33 UTC, kdhamric commented on docs/docs/tools-and-integrations/cypress.mdx
> +**Pokeshop Demo:** Clone the official Tracetest Pokeshop Demo App to your local machine.
Can we provide a link to this repo?

2024-01-02 20:34 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +Cypress is currently one of the top e2e testing frameworks, it is a great tool in its own right that allows you to replicate most of the production challenges you might encounter by allowinig develop
```suggestion
Cypress is currently one of the top e2e testing frameworks, it is a great tool in its own right that allows you to replicate most of the production challenges you might encounter by allowing developers to test the system from the user perspective. But, as with all of the tools that only test the UI portion application, you can only run validations against what the user would see while going through the flows.
```

2024-01-02 20:34 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +## The `@tracetest/cypress` npm package
```suggestion
## The `@tracetest/cypress` npm Package
```

2024-01-02 20:36 UTC, kdhamric reviewed
Marked a couple comments

2024-01-02 20:37 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +And the `docker-compose.e2e.yml` includes the and the [Tracetest Agent](/concepts/agent).
...includes the ??? and the... Missing text after the first 'the'.

2024-01-02 20:37 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +## The Cypress setup
```suggestion
## The Cypress Setup
```

2024-01-02 20:38 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +### The `home.cy` test script
```suggestion
### The `home.cy` Test Script
```

2024-01-02 20:38 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +### Tracetest library setup
```suggestion
### Tracetest Library Setup
```

2024-01-02 20:38 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +If you go to the `package.json` file you will find the inclusion of a Tracetest package for cypress `@tracetest/cypress`.
```suggestion
If you go to the `package.json` file you will find the inclusion of a Tracetest package for Cypress `@tracetest/cypress`.
```

2024-01-02 20:39 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +**OPTIONAL**: If you want to wait for the test to finish and break the cypress execution based on a failed Tracetest test, you can add the `after` hook and call the `summary` method.
```suggestion
**OPTIONAL**: If you want to wait for the test to finish and break the Cypress execution based on a failed Tracetest test, you can add the `after` hook and call the `summary` method.
```

2024-01-02 20:39 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +### Setting the environment variables
```suggestion
### Setting the Environment Variables
```

2024-01-02 20:40 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +### Running the tests
```suggestion
### Running the Tests
```

2024-01-02 20:41 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +The Tracetest library uses the same as the spec name for the trace-based tests, that way you can identify them more easily, it also fills some of the metadata directly from the cypress execution.
```suggestion
The Tracetest library uses the spec name for the trace-based tests. That way you can identify them more easily and it also fills in some of the metadata directly from the Cypress execution. 
```

2024-01-02 20:43 UTC, jfermi commented on docs/docs/tools-and-integrations/cypress.mdx
> +Starting with the click events and the fetch request from the client side, to the HTTP requests and database queries from the backend services, including async processes like the one showcased during
```suggestion
From the click events and the fetch request from the client side to the HTTP requests and database queries from the backend services, async processes like the one showcased during the import Pokemon test are included.
```

2024-01-02 20:43 UTC, jfermi reviewed
Some editing suggestions.

2024-01-03 12:02 UTC, adnanrahic requested changes
Added small suggestions for SEO.

2024-01-03 12:02 UTC, adnanrahic commented on docs/docs/tools-and-integrations/cypress.mdx
> +title: Running Tracetest with Cypress using the Pokeshop Demo
```suggestion
title: Trace-Based End to End Testing with Cypress and Tracetest
```

2024-01-03 12:02 UTC, adnanrahic commented on docs/docs/tools-and-integrations/cypress.mdx
> +Cypress is currently one of the top e2e testing frameworks, it is a great tool in its own right that allows you to replicate most of the production challenges you might encounter by allowing develope
```suggestion
Cypress is currently one of the top end to end testing frameworks, it is a great tool in its own right that allows you to replicate most of the production challenges you might encounter by allowing developers to test the system from the user perspective. But, as with all of the tools that only test the UI portion application, you can only run validations against what the user would see while going through the flows.
```

2024-01-03 20:00 UTC, jorgeepc approved these changes

2024-01-03 20:12 UTC, merged