Sample setup
kubeshop/tracetest pull request #494
Opened 2022-05-16 19:44 UTC by schoren

This PR...

## Changes

-

## Fixes

-

## Checklist

- [ ] tested locally
- [ ] added new dependencies
- [ ] updated the docs
- [ ] added a test

2022-05-16 21:24 UTC, mathnogueira commented on setup.sh
> +NAMESPACE="tractest"
```suggestion
NAMESPACE="tracetest"
```

2022-05-16 21:24 UTC, mathnogueira commented on setup.sh
> +      EXTENSION="$2"
Shouldn't it be `NAMESPACE="$2"?

2022-05-16 22:57 UTC, schoren commented on setup.sh
> +      EXTENSION="$2"
yup

2022-05-17 13:11 UTC, xoscar approved these changes
LGTM

2022-05-26 21:32 UTC, schoren commented on docs/installing.md
> +curl -L https://raw.githubusercontent.com/kubeshop/main/setup.sh | bash -s
this URL won't work until the PR is merged. You can try this command like this:

```
curl -L https://raw.githubusercontent.com/kubeshop/tracetest/sample-setup-script/setup.sh | bash -s
```

2022-05-26 22:13 UTC, kdhamric approved these changes
Looks good - this will help people get started quicker!

2022-05-27 12:20 UTC, mathnogueira requested changes
Installation fails on my machine when running on minikube :cry: 

![image](https://user-images.githubusercontent.com/2704737/170698087-d2040fa2-be0d-473b-9f1c-7dfee82fbab2.png)

2022-05-31 15:53 UTC, schoren commented
@mathnogueira I've done a lof of changes, so now you should be able to see it working. Just to be safe, you can do a cleanup (replace ` my-custom-namespace` for whatever namespaces you've used):

```
helm delete -n demo demo
helm delete -n my-custom-namespace tracetest
kubectl delete crd certificaterequests.cert-manager.io certificates.cert-manager.io challenges.acme.cert-manager.io clusterissuers.cert-manager.io issuers.cert-manager.io orders.acme.cert-manager.io jaegers.jaegertracing.io cert-manager-webhook
kubectl delete validatingwebhookconfigurations jaeger-operator-validating-webhook-configuration
kubectl delete mutatingwebhookconfigurations jaeger-operator-mutating-webhook-configuration
kubectl delete clusterrolebinding "jaeger-operator-proxy-rolebinding" "manager-rolebinding"
kubectl delete clusterrole "jaeger-operator-metrics-reader" "manager-role" "proxy-role"
kubectl delete ns observability cert-manager demo my-custom-namespace
```

2022-06-06 16:12 UTC, mathnogueira approved these changes

2022-06-06 19:08 UTC, kdhamric approved these changes
Looks good!

2022-06-06 19:08 UTC, jfermi commented on docs/installing.md
> +During the setup, we'll deploy Tracetest, and Postgres with Helm.
```suggestion
During the setup, we'll deploy Tracetest and Postgres with Helm.
```

2022-06-06 19:09 UTC, jfermi commented on docs/installing.md
> +For the architectural overview of the components please check the [Architecture](architecture.md) page.
```suggestion
For the architectural overview of the components, please check the [Architecture](architecture.md) page.
```

2022-06-06 19:09 UTC, jfermi commented on docs/installing.md
> +This command will install tracetest using the default settings. You can configure the following options:
```suggestion
This command will install Tracetest using the default settings. You can configure the following options:
```

2022-06-06 19:10 UTC, jfermi commented on docs/installing.md
> +Tracetest currently supports two traces backend: Jaeger and Grafana Tempo.
```suggestion
Tracetest currently supports two trace backends: Jaeger and Grafana Tempo.
```

2022-06-06 19:10 UTC, jfermi commented on docs/installing.md
> +The commands below will install Tracetest connecting to Jaeger tracing backend on `jaeger-query:16685`.
```suggestion
The commands below will install Tracetest connecting to the Jaeger tracing backend on `jaeger-query:16685`.
```

2022-06-06 19:11 UTC, jfermi commented on docs/installing.md
> +The commands below will install the Tracetest application connecting to Grafana Tempo tracing backend on `grafana-tempo:9095`:
```suggestion
The commands below will install the Tracetest application connecting to the Grafana Tempo tracing backend on `grafana-tempo:9095`:
```

2022-06-06 19:12 UTC, jfermi reviewed
Made a few editing suggestions.

2022-06-06 20:03 UTC, merged